// Deployment checkpoint: CFP v0.39.05 / 2026-08-16.
/*
 * Lobster Labz Alpha Lab server-side access gate.
 *
 * Required Cloudflare Worker secrets (never commit their values):
 *   LAB_PIN         shared tester PIN
 *   SESSION_SECRET  long random session-signing secret
 *
 * Every request reaches this Worker before Cloudflare's static asset binding.
 * Anonymous visitors receive only the login page; authenticated visitors can
 * load the game and its assets from public/.
 */

const SESSION_COOKIE = "llz_alpha_session";
const SESSION_TTL_SECONDS = 24 * 60 * 60;
const LOGIN_PATH = "/__alpha/login";
const LOGOUT_PATH = "/__alpha/logout";
const RATE_WINDOW_MS = 15 * 60 * 1000;
const RATE_LIMIT = 8;
const MAX_RATE_KEYS = 500;

// Best-effort edge-local throttle. For a larger public test, add a Cloudflare
// WAF rate-limit rule to the login endpoint as an additional layer.
const failedAttempts = new Map();
const encoder = new TextEncoder();

function base64Url(bytes) {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary)
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

async function hmac(secret, value) {
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign(
    "HMAC",
    key,
    encoder.encode(value)
  );
  return base64Url(new Uint8Array(signature));
}

function safeEqual(left, right) {
  if (
    typeof left !== "string" ||
    typeof right !== "string" ||
    left.length !== right.length
  ) {
    return false;
  }

  let difference = 0;
  for (let index = 0; index < left.length; index += 1) {
    difference |= left.charCodeAt(index) ^ right.charCodeAt(index);
  }
  return difference === 0;
}

async function pinMatches(supplied, expected, signingSecret) {
  const [suppliedDigest, expectedDigest] = await Promise.all([
    hmac(signingSecret, `pin:${supplied}`),
    hmac(signingSecret, `pin:${expected}`),
  ]);
  return safeEqual(suppliedDigest, expectedDigest);
}

function parseCookies(request) {
  const cookies = {};
  const header = request.headers.get("Cookie") || "";

  for (const part of header.split(";")) {
    const separator = part.indexOf("=");
    if (separator < 0) continue;
    const name = part.slice(0, separator).trim();
    const value = part.slice(separator + 1).trim();
    if (name) cookies[name] = value;
  }

  return cookies;
}

async function createSession(signingSecret) {
  const expires = Math.floor(Date.now() / 1000) + SESSION_TTL_SECONDS;
  const nonceBytes = crypto.getRandomValues(new Uint8Array(16));
  const payload = `v1.${expires}.${base64Url(nonceBytes)}`;
  return `${payload}.${await hmac(signingSecret, payload)}`;
}

async function hasValidSession(request, signingSecret) {
  if (!signingSecret) return false;

  const token = parseCookies(request)[SESSION_COOKIE] || "";
  const parts = token.split(".");
  if (parts.length !== 4 || parts[0] !== "v1") return false;

  const expires = Number(parts[1]);
  if (
    !Number.isSafeInteger(expires) ||
    expires <= Math.floor(Date.now() / 1000)
  ) {
    return false;
  }

  const payload = parts.slice(0, 3).join(".");
  const expected = await hmac(signingSecret, payload);
  return safeEqual(parts[3], expected);
}

function clientKey(request) {
  return request.headers.get("CF-Connecting-IP") || "unknown";
}

function isTrustedLoginRequest(request, url) {
  const fetchSite = (request.headers.get("Sec-Fetch-Site") || "").toLowerCase();

  // Fetch Metadata is generated by modern browsers and is more reliable than
  // comparing Origin to request.url when Cloudflare fronts a custom domain.
  if (fetchSite === "cross-site") return false;
  if (fetchSite === "same-origin") return true;

  const origin = request.headers.get("Origin");
  if (!origin || origin === "null") return true;

  const host = request.headers.get("Host");
  const publicOrigin = host ? `${url.protocol}//${host}` : url.origin;
  return origin === url.origin || origin === publicOrigin;
}

function pruneAttempts(now) {
  for (const [key, attempt] of failedAttempts) {
    if (now - attempt.startedAt >= RATE_WINDOW_MS) failedAttempts.delete(key);
  }

  while (failedAttempts.size > MAX_RATE_KEYS) {
    failedAttempts.delete(failedAttempts.keys().next().value);
  }
}

function isRateLimited(key) {
  const now = Date.now();
  pruneAttempts(now);
  const current = failedAttempts.get(key);

  if (!current || now - current.startedAt >= RATE_WINDOW_MS) {
    failedAttempts.set(key, { startedAt: now, count: 0 });
    return false;
  }

  return current.count >= RATE_LIMIT;
}

function recordFailure(key) {
  const now = Date.now();
  const current = failedAttempts.get(key);

  if (!current || now - current.startedAt >= RATE_WINDOW_MS) {
    failedAttempts.set(key, { startedAt: now, count: 1 });
    return;
  }

  current.count += 1;
}

function clearFailures(key) {
  failedAttempts.delete(key);
}

function securityHeaders(initialHeaders = {}) {
  const headers = new Headers(initialHeaders);
  headers.set("X-Content-Type-Options", "nosniff");
  headers.set("X-Frame-Options", "DENY");
  headers.set("Referrer-Policy", "no-referrer");
  // Voice chat remains available; unrelated sensitive browser APIs are denied.
  headers.set("Permissions-Policy", "camera=(), geolocation=(), payment=(), usb=()");
  headers.set("X-Robots-Tag", "noindex, nofollow, noarchive");
  return headers;
}

function htmlResponse(body, status = 200, extraHeaders = {}) {
  const headers = securityHeaders(extraHeaders);
  headers.set("Content-Type", "text/html; charset=UTF-8");
  headers.set("Cache-Control", "no-store, max-age=0");
  headers.set(
    "Content-Security-Policy",
    "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'"
  );
  return new Response(body, { status, headers });
}

function loginPage(message = "") {
  const notice = message
    ? `<p class="notice" role="alert">${message}</p>`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="robots" content="noindex, nofollow, noarchive">
  <title>Lobster Labz — Alpha Lab</title>
  <style>
    :root{color-scheme:dark;--ink:#0a0b0d;--panel:#181a1e;--cream:#f3eee4;--muted:#a7a8ac;--rust:#ff5a31;--blue:#7eaef4}
    *{box-sizing:border-box}
    html,body{margin:0;min-height:100%;background:var(--ink);color:var(--cream);font-family:"Courier New",monospace}
    body{display:grid;place-items:center;padding:calc(24px + env(safe-area-inset-top)) 24px calc(24px + env(safe-area-inset-bottom));background:radial-gradient(circle at 15% 15%,#25282d 0,#111214 44%,#090a0b 100%)}
    main{width:min(100%,520px);border:1px solid #696b70;border-radius:18px;background:linear-gradient(145deg,#252629,#151617);padding:clamp(24px,7vw,52px);box-shadow:12px 14px 0 #050607}
    .mark{display:flex;justify-content:space-between;gap:16px;align-items:center;color:var(--muted);font-size:12px;letter-spacing:2px;text-transform:uppercase}
    .mark b{color:var(--rust);font-size:15px}
    h1{font-family:Impact,"Arial Black",sans-serif;font-size:clamp(40px,11vw,70px);line-height:.9;letter-spacing:1px;margin:46px 0 18px;text-transform:uppercase}
    p{font-family:Arial,sans-serif;line-height:1.55;color:var(--muted);font-size:16px}
    form{margin-top:30px;display:grid;gap:12px}
    label{font-size:12px;letter-spacing:2px;text-transform:uppercase;color:var(--muted)}
    input{width:100%;border:1px solid #777b82;border-radius:8px;background:#0c0d0e;color:var(--cream);padding:14px 15px;font:700 18px/1 "Courier New",monospace;letter-spacing:2px}
    input:focus{outline:2px solid var(--blue);outline-offset:2px}
    button{margin-top:8px;border:2px solid var(--rust);border-radius:8px;background:var(--rust);color:#150d0a;padding:14px 18px;font:900 14px/1 "Courier New",monospace;letter-spacing:2px;text-transform:uppercase;cursor:pointer}
    button:hover{filter:brightness(1.1)}
    .notice{border-left:3px solid var(--rust);padding:10px 12px;margin:20px 0 0;color:#ffd2c7;background:#321914;font-size:14px}
    .fine{margin-top:26px;font-size:12px;letter-spacing:1px}
  </style>
</head>
<body>
  <main>
    <div class="mark"><span>LOBSTER LABZ</span><b>PRIVATE BAY</b></div>
    <h1>Alpha<br>Lab</h1>
    <p>Invited testers: enter the current access PIN to open this experimental build.</p>
    ${notice}
    <form method="post" action="${LOGIN_PATH}">
      <label for="pin">Access PIN</label>
      <input id="pin" name="pin" type="password" inputmode="text" autocomplete="off" autocapitalize="none" spellcheck="false" required autofocus>
      <button type="submit">Enter the lab</button>
    </form>
    <p class="fine">Access lasts 24 hours on this browser. Do not share the PIN publicly.</p>
  </main>
</body>
</html>`;
}

function redirect(location, cookie) {
  const headers = securityHeaders({
    Location: location,
    "Cache-Control": "no-store, max-age=0",
  });
  if (cookie) headers.append("Set-Cookie", cookie);
  return new Response(null, { status: 303, headers });
}

function clearSessionCookie() {
  return `${SESSION_COOKIE}=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Strict`;
}

function addAssetHeaders(response) {
  const headers = securityHeaders(response.headers);
  const contentType = headers.get("Content-Type") || "";

  // Keep HTML fresh while allowing private browser caching for large models,
  // images, and audio during long mobile/desktop test sessions.
  if (contentType.includes("text/html")) {
    headers.set("Cache-Control", "private, no-store, max-age=0");
  } else {
    headers.set("Cache-Control", "private, max-age=3600, must-revalidate");
  }
  headers.set("Vary", "Cookie");

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const signingSecret = env.SESSION_SECRET;

    // Fail closed: no game file can be served until both secrets exist.
    if (!env.LAB_PIN || !signingSecret) {
      return htmlResponse(
        loginPage("Alpha access is not configured yet."),
        503
      );
    }

    if (url.pathname === LOGIN_PATH) {
      if (request.method !== "POST") return redirect("/");

      if (!isTrustedLoginRequest(request, url)) {
        return htmlResponse(loginPage("That request was not accepted."), 403);
      }

      const key = clientKey(request);
      if (isRateLimited(key)) {
        return htmlResponse(
          loginPage("Too many attempts. Wait 15 minutes and try again."),
          429,
          { "Retry-After": "900" }
        );
      }

      let supplied = "";
      try {
        const form = await request.formData();
        supplied = String(form.get("pin") || "").trim();
      } catch {
        recordFailure(key);
        return htmlResponse(
          loginPage("That request could not be read. Try again."),
          400
        );
      }

      if (!(await pinMatches(supplied, String(env.LAB_PIN), signingSecret))) {
        recordFailure(key);
        return htmlResponse(loginPage("That PIN was not accepted."), 401);
      }

      clearFailures(key);
      const token = await createSession(signingSecret);
      const cookie = [
        `${SESSION_COOKIE}=${token}`,
        `Max-Age=${SESSION_TTL_SECONDS}`,
        "Path=/",
        "HttpOnly",
        "Secure",
        "SameSite=Strict",
      ].join("; ");
      return redirect("/", cookie);
    }

    if (url.pathname === LOGOUT_PATH) {
      return redirect("/", clearSessionCookie());
    }

    if (!(await hasValidSession(request, signingSecret))) {
      return htmlResponse(loginPage());
    }

    if (!env.ASSETS || typeof env.ASSETS.fetch !== "function") {
      return htmlResponse("Alpha asset binding is not configured.", 503);
    }

    const assetResponse = await env.ASSETS.fetch(request);
    return addAssetHeaders(assetResponse);
  },
};

